# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VideoCallExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VideoCallExample
	pod 'RemoteMonster', '~> 2.0'

  target 'VideoCallExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VideoCallExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
